export default [
  {
    id: "Ground",
    type: "glbModel",
    path: "models/ground.glb",
    texture: "textures/baked-ground.webp",
    header: "",
    content: "",
  },
  {
    id: "Building",
    type: "glbModel",
    path: "models/building.glb",
    texture: "textures/baked-building.webp",
    header: "Hala Sportowa Miejskiego Ośrodka Sportu i Rekreacji",
    content: "adres: Ks. Ignacego Skorupki 21, 90-532 Łódź.",
  },
  {
    id: "Scene",
    type: "glbModel",
    path: "models/low/low-scene.glb",
    texture: "textures/low/baked-low-scene.webp",
    header: "Scena koncertowa",
    content: "To tutaj będą grali artyści.",
  },
  {
    id: "Helpers",
    type: "glbModel",
    path: "models/helpers.glb",
    texture: "textures/baked-helpers.webp",
    header: "Namioty informacyjne i sanitarne",
    content: "W razie potrzeby, tutaj znajdziesz pomoc.",
  },
  {
    id: "Gastronomy",
    type: "glbModel",
    path: "models/low/low-gastronomy.glb",
    texture: "textures/low/baked-low-gastronomy.webp",
    header: "Gastronomia",
    content: "Chcesz coś zjeść? To miejsce jest dla Ciebie.",
  },
  {
    id: "Toitoi",
    type: "glbModel",
    path: "models/toitoi.glb",
    texture: "textures/baked-toitoi.webp",
    header: "Toalety",
    content: "Chyba nie trzeba tłumaczyć do czego służą.",
  },
  {
    id: "Entrance",
    type: "glbModel",
    path: "models/entrance.glb",
    texture: "textures/baked-entrance.webp",
    header: "Wejścia",
    content: "Tędy można wejść na teren festiwalu.",
  },
  {
    id: "Road",
    type: "glbModel",
    path: "models/road.glb",
    texture: "textures/baked-road.webp",
    header: "Ulica",
    content:
      "aleje Politechniki - ulica w Łodzi, mająca około 2,3 km długości.",
  },
];
